run:
  #  concurrency: 4
  #  allow-parallel-runners: true
  tests: true
  timeout: 5m
  skip-dirs:
    - bin
    - docs
  modules-download-mode: readonly
linters-settings:
  cyclop:
    skip-tests: true
  dupl:
    # tokens count to trigger issue, 150 by default
    threshold: 500
  decorder:
    dec-order:
      - type
      - const
      - var
      - func
    disable-dec-order-check: false
  errcheck:
    check-blank: false
    #    check-blank: true
    ignore: fmt:.*,[rR]ead|[wW]rite|[cC]lose,io:Copy
  gocritic:
    disabled-checks:
      - commentFormatting
  # revive:
  #   enable-all-rules: true
  #   rules:
  #     - name: cyclomatic
  #       disabled: true
  #     - name: argument-limit
  #       disabled: true
  #     - name: function-length
  #       disabled: true
  #     - name: function-result-limit
  #       disabled: true
  #     - name: line-length-limit
  #       disabled: true
  #     - name: file-header
  #       disabled: true
  #     - name: cognitive-complexity
  #       disabled: true
  #     - name: banned-characters
  #       disabled: true
  #     - name: max-public-structs
  #       disabled: true
  #     - name: add-constant
  #       disabled: true
  #     - name: unhandled-error
  #       disabled: true
  #     - name: var-naming
  #       disabled: true
  #     - name: deep-exit
  #       disabled: true
  #     - name: exported
  #       disabled: false
  #       arguments:
  #         - "disableStutteringCheck"
  #     - name: unused-parameter
  #       disabled: true
  #     - name: confusing-naming
  #       disabled: true
  #     - name: flag-parameter
  #       disabled: true
  #     - name: nested-structs
  #       disabled: true
linters:
  disable-all: true
  fast: false
  enable:
    - asciicheck
    - bodyclose
    - decorder
    # - depguard
    - dogsled
    - dupl
    - errcheck
    - exportloopref
    # - gci
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    # - godot
    - gofmt
    - goimports
    - gosec
    - gosimple
    - govet
    - importas
    - ineffassign
    - misspell
    - nakedret
    - prealloc
    # - revive
    - staticcheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace
# issues:
#   exclude-use-default: false
#   exclude-rules:
#     - path: _test\.go
#       linters:
#         - prealloc
#     - path: _test\.go
#       text: "G306:"
#       linters:
#         - gosec
#     - path: errors_test\.go
#       linters:
#         - unused
#     - path: http/example_test\.go
#       linters:
#         - errcheck
#         - bodyclose
